ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        shutdownGracePeriod = 3000
        shutdownTimeout = 10000
    }
    application {
        modules = [ id.primawash.api.ApplicationKt.module ]
    }
}
